// Centralized mock data for all HIMS modules

export const patients = [
  {
    id: 'PT-2024-001',
    name: 'Rajesh Kumar',
    age: 45,
    gender: 'Male',
    phone: '+91 98765 43210',
    bloodGroup: 'O+',
    status: 'Active',
    lastVisit: '2024-03-20',
    department: 'Cardiology',
    address: '12, MG Road, Mumbai',
    email: 'rajesh.k@email.com',
    idProof: 'Aadhaar - XXXX-XXXX-4521',
  },
  {
    id: 'PT-2024-002',
    name: 'Priya Sharma',
    age: 32,
    gender: 'Female',
    phone: '+91 87654 32109',
    bloodGroup: 'A+',
    status: 'Active',
    lastVisit: '2024-03-22',
    department: 'Gynecology',
    address: '45, Park Street, Delhi',
    email: 'priya.s@email.com',
    idProof: 'PAN - ABCDE1234F',
  },
  {
    id: 'PT-2024-003',
    name: 'Mohammed Ali',
    age: 58,
    gender: 'Male',
    phone: '+91 76543 21098',
    bloodGroup: 'B+',
    status: 'IPD',
    lastVisit: '2024-03-24',
    department: 'Orthopedics',
    address: '78, Jubilee Hills, Hyderabad',
    email: 'm.ali@email.com',
    idProof: 'Aadhaar - XXXX-XXXX-7834',
  },
  {
    id: 'PT-2024-004',
    name: 'Anita Desai',
    age: 28,
    gender: 'Female',
    phone: '+91 65432 10987',
    bloodGroup: 'AB+',
    status: 'Active',
    lastVisit: '2024-03-18',
    department: 'Dermatology',
    address: '23, Koramangala, Bangalore',
    email: 'anita.d@email.com',
    idProof: 'Passport - J8765432',
  },
  {
    id: 'PT-2024-005',
    name: 'Suresh Patel',
    age: 62,
    gender: 'Male',
    phone: '+91 54321 09876',
    bloodGroup: 'O-',
    status: 'Emergency',
    lastVisit: '2024-03-25',
    department: 'Neurology',
    address: '56, CG Road, Ahmedabad',
    email: 'suresh.p@email.com',
    idProof: 'Aadhaar - XXXX-XXXX-9012',
  },
  {
    id: 'PT-2024-006',
    name: 'Kavitha Nair',
    age: 40,
    gender: 'Female',
    phone: '+91 43210 98765',
    bloodGroup: 'A-',
    status: 'Active',
    lastVisit: '2024-03-21',
    department: 'ENT',
    address: '89, Marine Drive, Kochi',
    email: 'kavitha.n@email.com',
    idProof: 'DL - KA-1234567',
  },
  {
    id: 'PT-2024-007',
    name: 'Vikram Singh',
    age: 55,
    gender: 'Male',
    phone: '+91 32109 87654',
    bloodGroup: 'B-',
    status: 'Discharged',
    lastVisit: '2024-03-19',
    department: 'Pulmonology',
    address: '34, Sector 17, Chandigarh',
    email: 'vikram.s@email.com',
    idProof: 'Aadhaar - XXXX-XXXX-3456',
  },
  {
    id: 'PT-2024-008',
    name: 'Deepa Menon',
    age: 35,
    gender: 'Female',
    phone: '+91 21098 76543',
    bloodGroup: 'AB-',
    status: 'IPD',
    lastVisit: '2024-03-23',
    department: 'Oncology',
    address: '67, T Nagar, Chennai',
    email: 'deepa.m@email.com',
    idProof: 'Voter ID - MH/12/345/678',
  },
];

export const doctors = [
  {
    id: 'DR-001',
    name: 'Dr. Arun Mehta',
    department: 'Cardiology',
    specialization: 'Interventional Cardiology',
    phone: '+91 99887 76655',
    status: 'Available',
    experience: '18 years',
    consultationFee: 1500,
    rating: 4.8,
  },
  {
    id: 'DR-002',
    name: 'Dr. Sneha Reddy',
    department: 'Gynecology',
    specialization: 'High-risk Pregnancy',
    phone: '+91 88776 65544',
    status: 'In Consultation',
    experience: '12 years',
    consultationFee: 1200,
    rating: 4.9,
  },
  {
    id: 'DR-003',
    name: 'Dr. Rajan Iyer',
    department: 'Orthopedics',
    specialization: 'Joint Replacement',
    phone: '+91 77665 54433',
    status: 'Available',
    experience: '22 years',
    consultationFee: 1800,
    rating: 4.7,
  },
  {
    id: 'DR-004',
    name: 'Dr. Fatima Khan',
    department: 'Neurology',
    specialization: 'Stroke Management',
    phone: '+91 66554 43322',
    status: 'On Leave',
    experience: '15 years',
    consultationFee: 2000,
    rating: 4.6,
  },
  {
    id: 'DR-005',
    name: 'Dr. Prakash Joshi',
    department: 'Pulmonology',
    specialization: 'Respiratory Medicine',
    phone: '+91 55443 32211',
    status: 'Available',
    experience: '10 years',
    consultationFee: 1000,
    rating: 4.5,
  },
  {
    id: 'DR-006',
    name: 'Dr. Meera Krishnan',
    department: 'Dermatology',
    specialization: 'Cosmetic Dermatology',
    phone: '+91 44332 21100',
    status: 'In Consultation',
    experience: '8 years',
    consultationFee: 1100,
    rating: 4.8,
  },
  {
    id: 'DR-007',
    name: 'Dr. Sanjay Gupta',
    department: 'General Surgery',
    specialization: 'Laparoscopic Surgery',
    phone: '+91 33221 10099',
    status: 'In OT',
    experience: '20 years',
    consultationFee: 1600,
    rating: 4.9,
  },
  {
    id: 'DR-008',
    name: 'Dr. Lakshmi Rao',
    department: 'Oncology',
    specialization: 'Medical Oncology',
    phone: '+91 22110 09988',
    status: 'Available',
    experience: '14 years',
    consultationFee: 2500,
    rating: 4.7,
  },
];

export const appointments = [
  {
    id: 'APT-001',
    patientId: 'PT-2024-001',
    patientName: 'Rajesh Kumar',
    doctor: 'Dr. Arun Mehta',
    department: 'Cardiology',
    date: '2024-03-25',
    time: '09:00 AM',
    token: 1,
    status: 'Confirmed',
    type: 'Follow-up',
  },
  {
    id: 'APT-002',
    patientId: 'PT-2024-002',
    patientName: 'Priya Sharma',
    doctor: 'Dr. Sneha Reddy',
    department: 'Gynecology',
    date: '2024-03-25',
    time: '09:30 AM',
    token: 2,
    status: 'In Progress',
    type: 'Consultation',
  },
  {
    id: 'APT-003',
    patientId: 'PT-2024-004',
    patientName: 'Anita Desai',
    doctor: 'Dr. Meera Krishnan',
    department: 'Dermatology',
    date: '2024-03-25',
    time: '10:00 AM',
    token: 3,
    status: 'Waiting',
    type: 'New Visit',
  },
  {
    id: 'APT-004',
    patientId: 'PT-2024-006',
    patientName: 'Kavitha Nair',
    doctor: 'Dr. Prakash Joshi',
    department: 'Pulmonology',
    date: '2024-03-25',
    time: '10:30 AM',
    token: 4,
    status: 'Confirmed',
    type: 'Follow-up',
  },
  {
    id: 'APT-005',
    patientId: 'PT-2024-003',
    patientName: 'Mohammed Ali',
    doctor: 'Dr. Rajan Iyer',
    department: 'Orthopedics',
    date: '2024-03-25',
    time: '11:00 AM',
    token: 5,
    status: 'Waiting',
    type: 'Pre-Surgery',
  },
  {
    id: 'APT-006',
    patientId: 'PT-2024-007',
    patientName: 'Vikram Singh',
    doctor: 'Dr. Sanjay Gupta',
    department: 'General Surgery',
    date: '2024-03-26',
    time: '09:00 AM',
    token: 1,
    status: 'Scheduled',
    type: 'Consultation',
  },
];

export const beds = [
  {
    id: 'B-101',
    ward: 'General Ward A',
    floor: '1st Floor',
    type: 'General',
    status: 'Occupied',
    patient: 'Mohammed Ali',
    admissionDate: '2024-03-20',
    dailyRate: 2000,
  },
  {
    id: 'B-102',
    ward: 'General Ward A',
    floor: '1st Floor',
    type: 'General',
    status: 'Available',
    patient: null,
    admissionDate: null,
    dailyRate: 2000,
  },
  {
    id: 'B-103',
    ward: 'General Ward A',
    floor: '1st Floor',
    type: 'General',
    status: 'Maintenance',
    patient: null,
    admissionDate: null,
    dailyRate: 2000,
  },
  {
    id: 'B-201',
    ward: 'ICU',
    floor: '2nd Floor',
    type: 'ICU',
    status: 'Occupied',
    patient: 'Deepa Menon',
    admissionDate: '2024-03-23',
    dailyRate: 8000,
  },
  {
    id: 'B-202',
    ward: 'ICU',
    floor: '2nd Floor',
    type: 'ICU',
    status: 'Available',
    patient: null,
    admissionDate: null,
    dailyRate: 8000,
  },
  {
    id: 'B-203',
    ward: 'ICU',
    floor: '2nd Floor',
    type: 'ICU',
    status: 'Occupied',
    patient: 'Suresh Patel',
    admissionDate: '2024-03-24',
    dailyRate: 8000,
  },
  {
    id: 'B-301',
    ward: 'Private Room',
    floor: '3rd Floor',
    type: 'Private',
    status: 'Available',
    patient: null,
    admissionDate: null,
    dailyRate: 5000,
  },
  {
    id: 'B-302',
    ward: 'Private Room',
    floor: '3rd Floor',
    type: 'Private',
    status: 'Occupied',
    patient: 'Vikram Singh',
    admissionDate: '2024-03-19',
    dailyRate: 5000,
  },
  {
    id: 'B-401',
    ward: 'Maternity Ward',
    floor: '4th Floor',
    type: 'Maternity',
    status: 'Available',
    patient: null,
    admissionDate: null,
    dailyRate: 3500,
  },
  {
    id: 'B-402',
    ward: 'Maternity Ward',
    floor: '4th Floor',
    type: 'Maternity',
    status: 'Occupied',
    patient: 'Priya Sharma',
    admissionDate: '2024-03-22',
    dailyRate: 3500,
  },
];

export const labTests = [
  {
    id: 'LAB-001',
    patientId: 'PT-2024-001',
    patientName: 'Rajesh Kumar',
    testName: 'Complete Blood Count',
    requestedBy: 'Dr. Arun Mehta',
    date: '2024-03-25',
    status: 'Completed',
    priority: 'Normal',
    results: 'Hb: 14.2, WBC: 7500, Platelets: 250000',
  },
  {
    id: 'LAB-002',
    patientId: 'PT-2024-003',
    patientName: 'Mohammed Ali',
    testName: 'Lipid Profile',
    requestedBy: 'Dr. Rajan Iyer',
    date: '2024-03-25',
    status: 'In Progress',
    priority: 'Urgent',
    results: null,
  },
  {
    id: 'LAB-003',
    patientId: 'PT-2024-005',
    patientName: 'Suresh Patel',
    testName: 'Blood Glucose (Fasting)',
    requestedBy: 'Dr. Fatima Khan',
    date: '2024-03-25',
    status: 'Pending',
    priority: 'Urgent',
    results: null,
  },
  {
    id: 'LAB-004',
    patientId: 'PT-2024-002',
    patientName: 'Priya Sharma',
    testName: 'Thyroid Profile',
    requestedBy: 'Dr. Sneha Reddy',
    date: '2024-03-24',
    status: 'Completed',
    priority: 'Normal',
    results: 'TSH: 3.2, T3: 1.1, T4: 8.5',
  },
  {
    id: 'LAB-005',
    patientId: 'PT-2024-008',
    patientName: 'Deepa Menon',
    testName: 'Tumor Markers',
    requestedBy: 'Dr. Lakshmi Rao',
    date: '2024-03-24',
    status: 'Completed',
    priority: 'Urgent',
    results: 'CEA: 2.1, AFP: 4.5',
  },
];

export const radiology = [
  {
    id: 'RAD-001',
    patientId: 'PT-2024-003',
    patientName: 'Mohammed Ali',
    scanType: 'X-Ray',
    bodyPart: 'Right Knee',
    requestedBy: 'Dr. Rajan Iyer',
    date: '2024-03-25',
    status: 'Completed',
    report: 'Mild degenerative changes noted',
  },
  {
    id: 'RAD-002',
    patientId: 'PT-2024-005',
    patientName: 'Suresh Patel',
    scanType: 'MRI',
    bodyPart: 'Brain',
    requestedBy: 'Dr. Fatima Khan',
    date: '2024-03-25',
    status: 'Scheduled',
    report: null,
  },
  {
    id: 'RAD-003',
    patientId: 'PT-2024-008',
    patientName: 'Deepa Menon',
    scanType: 'CT Scan',
    bodyPart: 'Abdomen',
    requestedBy: 'Dr. Lakshmi Rao',
    date: '2024-03-24',
    status: 'Completed',
    report: 'No significant abnormality detected',
  },
  {
    id: 'RAD-004',
    patientId: 'PT-2024-001',
    patientName: 'Rajesh Kumar',
    scanType: 'Echocardiogram',
    bodyPart: 'Heart',
    requestedBy: 'Dr. Arun Mehta',
    date: '2024-03-23',
    status: 'Completed',
    report: 'LVEF 55%, No valvular abnormalities',
  },
];

export const bloodBank = {
  stock: [
    { group: 'A+', units: 45, lastUpdated: '2024-03-25' },
    { group: 'A-', units: 12, lastUpdated: '2024-03-25' },
    { group: 'B+', units: 38, lastUpdated: '2024-03-25' },
    { group: 'B-', units: 8, lastUpdated: '2024-03-24' },
    { group: 'AB+', units: 15, lastUpdated: '2024-03-25' },
    { group: 'AB-', units: 5, lastUpdated: '2024-03-23' },
    { group: 'O+', units: 52, lastUpdated: '2024-03-25' },
    { group: 'O-', units: 18, lastUpdated: '2024-03-25' },
  ],
  donors: [
    {
      id: 'BD-001',
      name: 'Amit Verma',
      bloodGroup: 'O+',
      phone: '+91 98765 11111',
      lastDonation: '2024-01-15',
      status: 'Eligible',
    },
    {
      id: 'BD-002',
      name: 'Sita Devi',
      bloodGroup: 'A+',
      phone: '+91 98765 22222',
      lastDonation: '2024-02-20',
      status: 'Eligible',
    },
    {
      id: 'BD-003',
      name: 'Rahul Kapoor',
      bloodGroup: 'B+',
      phone: '+91 98765 33333',
      lastDonation: '2024-03-10',
      status: 'Cooldown',
    },
  ],
  requests: [
    {
      id: 'BR-001',
      patientName: 'Mohammed Ali',
      bloodGroup: 'B+',
      units: 2,
      requestedBy: 'Dr. Rajan Iyer',
      date: '2024-03-25',
      status: 'Approved',
      urgency: 'Urgent',
    },
    {
      id: 'BR-002',
      patientName: 'Deepa Menon',
      bloodGroup: 'AB-',
      units: 1,
      requestedBy: 'Dr. Lakshmi Rao',
      date: '2024-03-25',
      status: 'Pending',
      urgency: 'Normal',
    },
  ],
};

export const medicines = [
  {
    id: 'MED-001',
    name: 'Paracetamol 500mg',
    category: 'Analgesic',
    stock: 5000,
    batchNo: 'PCM-2024-A1',
    expiryDate: '2025-06-15',
    supplier: 'Sun Pharma',
    unitPrice: 2.5,
    reorderLevel: 1000,
  },
  {
    id: 'MED-002',
    name: 'Amoxicillin 250mg',
    category: 'Antibiotic',
    stock: 3200,
    batchNo: 'AMX-2024-B2',
    expiryDate: '2025-03-20',
    supplier: 'Cipla',
    unitPrice: 8.0,
    reorderLevel: 500,
  },
  {
    id: 'MED-003',
    name: 'Metformin 500mg',
    category: 'Antidiabetic',
    stock: 4500,
    batchNo: 'MTF-2024-C3',
    expiryDate: '2025-09-10',
    supplier: "Dr. Reddy's",
    unitPrice: 5.5,
    reorderLevel: 800,
  },
  {
    id: 'MED-004',
    name: 'Amlodipine 5mg',
    category: 'Antihypertensive',
    stock: 2800,
    batchNo: 'AML-2024-D4',
    expiryDate: '2025-12-01',
    supplier: 'Lupin',
    unitPrice: 12.0,
    reorderLevel: 500,
  },
  {
    id: 'MED-005',
    name: 'Omeprazole 20mg',
    category: 'Antacid',
    stock: 180,
    batchNo: 'OMP-2024-E5',
    expiryDate: '2024-05-30',
    supplier: 'Torrent',
    unitPrice: 6.0,
    reorderLevel: 400,
  },
  {
    id: 'MED-006',
    name: 'Cetirizine 10mg',
    category: 'Antihistamine',
    stock: 3600,
    batchNo: 'CTZ-2024-F6',
    expiryDate: '2025-08-25',
    supplier: 'Sun Pharma',
    unitPrice: 3.0,
    reorderLevel: 600,
  },
  {
    id: 'MED-007',
    name: 'Atorvastatin 10mg',
    category: 'Statin',
    stock: 2100,
    batchNo: 'ATV-2024-G7',
    expiryDate: '2025-11-15',
    supplier: 'Cipla',
    unitPrice: 15.0,
    reorderLevel: 400,
  },
  {
    id: 'MED-008',
    name: 'Insulin Glargine',
    category: 'Antidiabetic',
    stock: 320,
    batchNo: 'INS-2024-H8',
    expiryDate: '2024-08-01',
    supplier: 'Novo Nordisk',
    unitPrice: 850.0,
    reorderLevel: 100,
  },
];

export const invoices = [
  {
    id: 'INV-001',
    patientId: 'PT-2024-001',
    patientName: 'Rajesh Kumar',
    type: 'OPD',
    amount: 3500,
    paid: 3500,
    balance: 0,
    date: '2024-03-20',
    paymentMode: 'UPI',
    status: 'Paid',
  },
  {
    id: 'INV-002',
    patientId: 'PT-2024-003',
    patientName: 'Mohammed Ali',
    type: 'IPD',
    amount: 45000,
    paid: 20000,
    balance: 25000,
    date: '2024-03-22',
    paymentMode: 'Insurance',
    status: 'Partial',
  },
  {
    id: 'INV-003',
    patientId: 'PT-2024-008',
    patientName: 'Deepa Menon',
    type: 'IPD',
    amount: 120000,
    paid: 0,
    balance: 120000,
    date: '2024-03-23',
    paymentMode: 'Pending',
    status: 'Unpaid',
  },
  {
    id: 'INV-004',
    patientId: 'PT-2024-004',
    patientName: 'Anita Desai',
    type: 'OPD',
    amount: 2200,
    paid: 2200,
    balance: 0,
    date: '2024-03-18',
    paymentMode: 'Card',
    status: 'Paid',
  },
  {
    id: 'INV-005',
    patientId: 'PT-2024-006',
    patientName: 'Kavitha Nair',
    type: 'OPD',
    amount: 1800,
    paid: 1800,
    balance: 0,
    date: '2024-03-21',
    paymentMode: 'Cash',
    status: 'Paid',
  },
];

export const insuranceClaims = [
  {
    id: 'CLM-001',
    patientName: 'Mohammed Ali',
    policyNo: 'HI-2024-98765',
    insurer: 'Star Health',
    claimAmount: 45000,
    approvedAmount: 35000,
    status: 'Approved',
    date: '2024-03-22',
    preAuth: true,
  },
  {
    id: 'CLM-002',
    patientName: 'Deepa Menon',
    policyNo: 'HI-2024-87654',
    insurer: 'HDFC Ergo',
    claimAmount: 120000,
    approvedAmount: null,
    status: 'Under Review',
    date: '2024-03-23',
    preAuth: true,
  },
  {
    id: 'CLM-003',
    patientName: 'Vikram Singh',
    policyNo: 'HI-2024-76543',
    insurer: 'ICICI Lombard',
    claimAmount: 25000,
    approvedAmount: 25000,
    status: 'Settled',
    date: '2024-03-19',
    preAuth: false,
  },
];

export const users = [
  {
    id: 'USR-001',
    name: 'Admin User',
    email: 'admin@medsphere.com',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2024-03-25 09:00 AM',
    department: 'Administration',
  },
  {
    id: 'USR-002',
    name: 'Dr. Arun Mehta',
    email: 'arun.m@medsphere.com',
    role: 'Doctor',
    status: 'Active',
    lastLogin: '2024-03-25 08:30 AM',
    department: 'Cardiology',
  },
  {
    id: 'USR-003',
    name: 'Nurse Priya',
    email: 'priya.n@medsphere.com',
    role: 'Nurse',
    status: 'Active',
    lastLogin: '2024-03-25 07:00 AM',
    department: 'ICU',
  },
  {
    id: 'USR-004',
    name: 'Receptionist Anu',
    email: 'anu.r@medsphere.com',
    role: 'Receptionist',
    status: 'Active',
    lastLogin: '2024-03-25 08:00 AM',
    department: 'Front Desk',
  },
  {
    id: 'USR-005',
    name: 'Lab Tech Vijay',
    email: 'vijay.l@medsphere.com',
    role: 'Lab Technician',
    status: 'Active',
    lastLogin: '2024-03-25 08:15 AM',
    department: 'Pathology',
  },
  {
    id: 'USR-006',
    name: 'Pharmacist Suman',
    email: 'suman.p@medsphere.com',
    role: 'Pharmacist',
    status: 'Active',
    lastLogin: '2024-03-25 08:45 AM',
    department: 'Pharmacy',
  },
  {
    id: 'USR-007',
    name: 'Accountant Raj',
    email: 'raj.a@medsphere.com',
    role: 'Accountant',
    status: 'Inactive',
    lastLogin: '2024-03-20 10:00 AM',
    department: 'Finance',
  },
];

export const ambulances = [
  {
    id: 'AMB-001',
    vehicleNo: 'MH-01-AB-1234',
    type: 'Advanced Life Support',
    driver: 'Ramesh Kumar',
    status: 'Available',
    lastService: '2024-03-10',
    location: 'Hospital Bay 1',
  },
  {
    id: 'AMB-002',
    vehicleNo: 'MH-01-CD-5678',
    type: 'Basic Life Support',
    driver: 'Sunil Yadav',
    status: 'On Duty',
    lastService: '2024-03-05',
    location: 'En-route - Andheri',
  },
  {
    id: 'AMB-003',
    vehicleNo: 'MH-01-EF-9012',
    type: 'Patient Transport',
    driver: 'Mohan Das',
    status: 'Available',
    lastService: '2024-03-15',
    location: 'Hospital Bay 2',
  },
  {
    id: 'AMB-004',
    vehicleNo: 'MH-01-GH-3456',
    type: 'Advanced Life Support',
    driver: 'Vijay Patil',
    status: 'Maintenance',
    lastService: '2024-02-28',
    location: 'Service Center',
  },
];

export const inventory = [
  {
    id: 'INV-M-001',
    name: 'Surgical Gloves (Box)',
    category: 'Medical Supply',
    stock: 450,
    reorderLevel: 100,
    unitPrice: 350,
    supplier: 'MedPro Supplies',
    lastRestocked: '2024-03-20',
  },
  {
    id: 'INV-M-002',
    name: 'N95 Masks (Box)',
    category: 'Medical Supply',
    stock: 200,
    reorderLevel: 50,
    unitPrice: 800,
    supplier: 'SafeGuard Medical',
    lastRestocked: '2024-03-18',
  },
  {
    id: 'INV-M-003',
    name: 'IV Cannula (Pack)',
    category: 'Medical Supply',
    stock: 30,
    reorderLevel: 50,
    unitPrice: 250,
    supplier: 'MedPro Supplies',
    lastRestocked: '2024-03-10',
  },
  {
    id: 'INV-N-001',
    name: 'Bed Sheets (Set)',
    category: 'Non-Medical',
    stock: 150,
    reorderLevel: 30,
    unitPrice: 450,
    supplier: 'Hospital Linens Co.',
    lastRestocked: '2024-03-15',
  },
  {
    id: 'INV-N-002',
    name: 'Sanitizer (5L)',
    category: 'Non-Medical',
    stock: 80,
    reorderLevel: 20,
    unitPrice: 500,
    supplier: 'CleanSafe India',
    lastRestocked: '2024-03-12',
  },
  {
    id: 'INV-M-004',
    name: 'Syringes 5ml (Box)',
    category: 'Medical Supply',
    stock: 600,
    reorderLevel: 150,
    unitPrice: 200,
    supplier: 'MedPro Supplies',
    lastRestocked: '2024-03-22',
  },
];

export const surgeries = [
  {
    id: 'SUR-001',
    patientName: 'Mohammed Ali',
    type: 'Knee Replacement',
    surgeon: 'Dr. Rajan Iyer',
    ot: 'OT-1',
    date: '2024-03-26',
    time: '10:00 AM',
    status: 'Scheduled',
    anesthetist: 'Dr. Vinod',
    estimatedDuration: '3 hours',
  },
  {
    id: 'SUR-002',
    patientName: 'Vikram Singh',
    type: 'Appendectomy',
    surgeon: 'Dr. Sanjay Gupta',
    ot: 'OT-2',
    date: '2024-03-25',
    time: '02:00 PM',
    status: 'In Progress',
    anesthetist: 'Dr. Meena',
    estimatedDuration: '1.5 hours',
  },
  {
    id: 'SUR-003',
    patientName: 'Deepa Menon',
    type: 'Tumor Excision',
    surgeon: 'Dr. Lakshmi Rao',
    ot: 'OT-1',
    date: '2024-03-27',
    time: '09:00 AM',
    status: 'Scheduled',
    anesthetist: 'Dr. Vinod',
    estimatedDuration: '4 hours',
  },
];

export const nurseVitals = [
  {
    id: 'V-001',
    patientId: 'PT-2024-003',
    patientName: 'Mohammed Ali',
    bp: '130/85',
    pulse: 78,
    temp: 98.6,
    oxygen: 97,
    recordedBy: 'Nurse Priya',
    time: '2024-03-25 08:00 AM',
    notes: 'Stable condition',
  },
  {
    id: 'V-002',
    patientId: 'PT-2024-005',
    patientName: 'Suresh Patel',
    bp: '145/92',
    pulse: 88,
    temp: 99.2,
    oxygen: 95,
    recordedBy: 'Nurse Priya',
    time: '2024-03-25 08:15 AM',
    notes: 'Mild fever, monitoring',
  },
  {
    id: 'V-003',
    patientId: 'PT-2024-008',
    patientName: 'Deepa Menon',
    bp: '118/76',
    pulse: 72,
    temp: 98.4,
    oxygen: 98,
    recordedBy: 'Nurse Kavita',
    time: '2024-03-25 08:30 AM',
    notes: 'Post-op recovery normal',
  },
];

export const alerts = [
  {
    id: 'ALT-001',
    type: 'Emergency',
    message: 'Critical patient in ER - Bed B-203',
    time: '5 min ago',
    read: false,
    priority: 'high',
  },
  {
    id: 'ALT-002',
    type: 'Inventory',
    message: 'IV Cannula stock below reorder level',
    time: '15 min ago',
    read: false,
    priority: 'medium',
  },
  {
    id: 'ALT-003',
    type: 'Appointment',
    message: 'Dr. Fatima Khan on leave - 3 appointments rescheduled',
    time: '1 hour ago',
    read: true,
    priority: 'low',
  },
  {
    id: 'ALT-004',
    type: 'Lab',
    message: 'Urgent lab results ready for PT-2024-003',
    time: '30 min ago',
    read: false,
    priority: 'high',
  },
  {
    id: 'ALT-005',
    type: 'System',
    message: 'Scheduled backup completed successfully',
    time: '2 hours ago',
    read: true,
    priority: 'low',
  },
  {
    id: 'ALT-006',
    type: 'Blood Bank',
    message: 'B- blood type critically low (8 units)',
    time: '45 min ago',
    read: false,
    priority: 'high',
  },
  {
    id: 'ALT-007',
    type: 'Pharmacy',
    message: 'Omeprazole 20mg nearing expiry (May 2024)',
    time: '3 hours ago',
    read: true,
    priority: 'medium',
  },
];

export const dashboardStats = {
  totalPatients: 12847,
  todayOPD: 142,
  todayIPD: 68,
  totalBeds: 200,
  occupiedBeds: 148,
  availableBeds: 44,
  maintenanceBeds: 8,
  todayRevenue: 485000,
  monthlyRevenue: 12500000,
  pendingBills: 28,
  emergencyCases: 5,
  surgeriesToday: 3,
  labTestsPending: 23,
  criticalPatients: 7,
};

export const revenueData = [
  { month: 'Jan', revenue: 9800000, expenses: 7200000 },
  { month: 'Feb', revenue: 10200000, expenses: 7500000 },
  { month: 'Mar', revenue: 12500000, expenses: 8100000 },
  { month: 'Apr', revenue: 11000000, expenses: 7800000 },
  { month: 'May', revenue: 11800000, expenses: 8000000 },
  { month: 'Jun', revenue: 13200000, expenses: 8500000 },
];

export const departmentStats = [
  { name: 'Cardiology', patients: 320, revenue: 2800000 },
  { name: 'Orthopedics', patients: 280, revenue: 2400000 },
  { name: 'Gynecology', patients: 250, revenue: 1800000 },
  { name: 'Neurology', patients: 190, revenue: 2100000 },
  { name: 'Oncology', patients: 150, revenue: 3200000 },
  { name: 'General', patients: 580, revenue: 1500000 },
];

export const patientFlowData = [
  { time: '6AM', opd: 5, emergency: 2, ipd: 0 },
  { time: '8AM', opd: 25, emergency: 4, ipd: 3 },
  { time: '10AM', opd: 45, emergency: 6, ipd: 5 },
  { time: '12PM', opd: 35, emergency: 8, ipd: 2 },
  { time: '2PM', opd: 30, emergency: 5, ipd: 4 },
  { time: '4PM', opd: 20, emergency: 7, ipd: 3 },
  { time: '6PM', opd: 15, emergency: 9, ipd: 1 },
  { time: '8PM', opd: 5, emergency: 6, ipd: 2 },
];

export const auditLogs = [
  {
    id: 'LOG-001',
    user: 'Admin User',
    action: 'Created User',
    target: 'Pharmacist Suman',
    timestamp: '2024-03-25 09:15 AM',
    ip: '192.168.1.100',
  },
  {
    id: 'LOG-002',
    user: 'Dr. Arun Mehta',
    action: 'Updated EMR',
    target: 'PT-2024-001',
    timestamp: '2024-03-25 09:30 AM',
    ip: '192.168.1.105',
  },
  {
    id: 'LOG-003',
    user: 'Receptionist Anu',
    action: 'Registered Patient',
    target: 'PT-2024-008',
    timestamp: '2024-03-25 08:45 AM',
    ip: '192.168.1.102',
  },
  {
    id: 'LOG-004',
    user: 'Nurse Priya',
    action: 'Recorded Vitals',
    target: 'PT-2024-003',
    timestamp: '2024-03-25 08:00 AM',
    ip: '192.168.1.110',
  },
  {
    id: 'LOG-005',
    user: 'Pharmacist Suman',
    action: 'Dispensed Medicine',
    target: 'MED-001, MED-003',
    timestamp: '2024-03-25 09:00 AM',
    ip: '192.168.1.108',
  },
];
